### ISSUE TITLE
gpg cannot decrypt files encrypted on other platforms.

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/gpgport#16] opened 2023-09-19 20:14 UTC
```
gpg -d --batch --passphrase asdf < stuff
gpg: can't mmap pool of 32768 bytes: EDC5128I No such device. - using malloc
gpg: Please note that you don't have secure memory on this system
token 50331735: pid   50331735, user      CCW, started Tue Sep 19 16:09:02 2023
gpg: AES256.CFB encrypted data
gpg: encrypted with 1 passphrase
gpg: uncompressing failed: Unknown compression algorithm
```
The last message is the problem.

stuff was created with `echo hello world | gpg -c --batch --passphrase asdf > stuff` on other platform.

**Comment by ccw-1** [comment] 2023-11-08 04:02
Simpler test case:
`echo hello world | gpg -c --batch --passphrase 123456 -o - 2>/dev/null | gpg -d --batch --passphrase 123456 2>/dev/null`

The expected result is `hello world`

**Comment by HarithaIBM** [comment] 2023-11-08 05:01
> Simpler test case: `echo hello world | gpg -c --batch --passphrase 123456 -o - 2>/dev/null | gpg -d --batch --passphrase 123456 2>/dev/null`
> 
> The expected result is `hello world`
I have arrived at the cross platform issue fix. I am testing it. This should help me in testing , thank you for sharing.

**Comment by ccw-1** [comment] 2023-11-18 15:10
Is it in the current meta? I am still getting 
```


token 33556842: pid   33556842, user      CCW, started Sat Nov 18 10:08:21 2023
token 33556916: pid   33556916, user      CCW, started Sat Nov 18 09:50:37 2023
token 33557058: pid   33557058, user      CCW, started Sat Nov 18 10:08:21 2023
CCW@localhost [~]gpg --version
gpg: can't mmap pool of 32768 bytes: EDC5128I No such device. - using malloc
gpg: Please note that you don't have secure memory on this system
token 67109357: pid   67109357, user      CCW, started Sat Nov 18 10:08:01 2023
token 67110114: pid   67110114, user      CCW, started Sat Nov 18 10:08:01 2023
token 33555926: pid   33555926, user      CCW, started Sat Nov 18 09:50:37 2023
token 67110407: pid   67110407, user      CCW, started Sat Nov 18 10:06:44 2023
token 1977: pid       1977, user      CCW, started Fri Nov 17 16:45:27 2023
token 33556916: pid   33556916, user      CCW, started Sat Nov 18 09:50:37 2023
token 50334274: pid   50334274, user      CCW, started Sat Nov 18 10:08:43 2023
gpg (GnuPG) 2.4.0
libgcrypt 1.10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/ccw/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB
CCW@localhost [~]echo hello world | gpg -c --batch --passphrase 123456 -o - 2>/dev/null | gpg -d --batch --passphrase 123456 2>/dev/null
token 50331682: pid   50331682, user      CCW, started Sat Nov 18 10:08:45 2023
token 67109357: pid   67109357, user      CCW, started Sat Nov 18 10:08:01 2023
token 50332685: pid   50332685, user      CCW, started Sat Nov 18 10:08:45 2023

```

**Comment by HarithaIBM** [comment] 2023-11-23 14:58
@ccw-1 Hi, It is in latest gpg, please run upgrade on gpg.

**Comment by ccw-1** [comment] 2023-12-19 13:58
I ran the latest build, but I am still seeing the same problem, could there be a build problem somewhere?
```
gpg --version
gpg: can't mmap pool of 32768 bytes: EDC5128I No such device. - using malloc
gpg: Please note that you don't have secure memory on this system
token 16777248: pid   16777248, user      CCW, started Fri Dec 15 19:40:52 2023
token 33: pid         33, user      CCW, started Fri Dec 15 19:40:52 2023
token 730: pid        730, user      CCW, started Tue Dec 19 08:47:01 2023
token 16778186: pid   16778186, user      CCW, started Tue Dec 19 08:47:01 2023
token 2469: pid       2469, user      CCW, started Tue Dec 19 08:55:44 2023
token 83888711: pid   83888711, user      CCW, started Tue Dec 19 08:55:44 2023
token 50334309: pid   50334309, user      CCW, started Tue Dec 19 08:55:45 2023
token 2774: pid       2774, user      CCW, started Tue Dec 19 08:55:45 2023
token 33557224: pid   33557224, user      CCW, started Tue Dec 19 08:57:27 2023
gpg (GnuPG) 2.4.3
libgcrypt 1.10.2
Copyright (C) 2023 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/ccw/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB
# echo hello world | gpg -c --batch --passphrase 123456 -o - 2>/dev/null | gpg -d --batch --passphrase 123456 2>/dev/null
token 16777248: pid   16777248, user      CCW, started Fri Dec 15 19:40:52 2023
token 33: pid         33, user      CCW, started Fri Dec 15 19:40:52 2023
token 730: pid        730, user      CCW, started Tue Dec 19 08:47:01 2023
token 16778186: pid   16778186, user      CCW, started Tue Dec 19 08:47:01 2023
token 2178: pid       2178, user      CCW, started Tue Dec 19 08:57:35 2023
```

**Comment by HarithaIBM** [comment] 2024-01-04 06:25
@ccw-1 Hi CW, can you please try using the latest gpg. Please run "`zopen upgrade gpg`" and try running the command
`echo hello world | gpg -c --batch --passphrase 123456 -o - 2>/dev/null | gpg -d --batch --passphrase 123456 2>/dev/null`.

**Comment by ccw-1** [comment] 2024-01-04 06:26
Today's build was ok!

**Comment by HarithaIBM** [comment] 2024-01-05 14:38
Ok , thank you. So, is it ok to close this issue?

**Comment by HarithaIBM** [comment] 2024-01-09 15:30
As per the discussion, the issue is fixed on latest build. Closing it.

**Closed by HarithaIBM** 2024-01-09 15:30 UTC
